language: node_js
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev build-essential graphviz cargo
  - cargo install svgbob_cli
  - export PATH="$PATH:$HOME/.cargo/bin"